apiVersion: v1
kind: Service
metadata:
  name: aegis-agent-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: aegis-agent
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
